{
 "title": "All Services Logs",
 "tags": [
  "logs",
  "all-services"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "URL Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"spring-boot\",filename=~\".*/url-service.log\"}"
    }
   ]
  },
  {
   "title": "Redirect Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"spring-boot\",filename=~\".*/redirect-service.log\"}"
    }
   ]
  },
  {
   "title": "Click Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"spring-boot\",filename=~\".*/click-service.log\"}"
    }
   ]
  }
 ]
}